# Generated by Django 4.1.1 on 2022-09-14 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_updateorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='updateorder',
            new_name='OrderUpdate',
        ),
    ]
